function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 22-Oct-2022 09:35:59

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create mesh
mesh1 = mesh(xdata1,ydata1,zdata1,'Parent',axes1);

% The following line demonstrates an alternative way to create a data tip.
% datatip(mesh1,0.4,0.5,98.6972333198216);
% Create datatip
datatip(mesh1,'DataIndex',6);

% Create zlabel
zlabel('Endurance Time (s)','FontSize',18);

% Create ylabel
ylabel('COP','FontSize',18);

% Create xlabel
xlabel('Weight Distribution','FontSize',18);

% Create title
title('Endurance time sensitivity to COP and Weight Distribution',...
    'FontWeight','bold',...
    'FontSize',24);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.400000005960464 0.490909091450952]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.418181825767864 0.600000023841858]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[74.3699598833504 92.5517780651686]);
view(axes1,[-3.0966193757573 -1.39900381061023]);
grid(axes1,'on');
hold(axes1,'off');
% Create colorbar
colorbar(axes1);

