function AccelLLTD(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 22-Oct-2022 12:46:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot(X1,Y1,'o',X1,Y1)


% Create ylabel
ylabel('Accel Time (s)','FontSize',18);

% Create xlabel
xlabel('LLTD','FontSize',18);

% Create title
title('Accel time sensitivty to LLTD','FontWeight','bold','FontSize',24);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.31089233268391 0.765437787229365]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[3.1636363809759 5.43636365370317]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XMinorGrid','on','YMinorGrid','on','ZMinorGrid','on');
