function EnduranceWeight(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 22-Oct-2022 11:03:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot(X1./4.4482216153,Y1,'o',X1./4.4482216153,Y1)
% Create ylabel
ylabel('Endurance Time (s)','FontSize',18);

% Create xlabel
xlabel('Weight (lbs)','FontSize',18);

% Create title
title('Endurance time sensitivity to Weight increase','FontWeight','bold',...
    'FontSize',24);

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XMinorGrid','on','YMinorGrid','on','ZMinorGrid','on');
