function AccelCOPandWD(xdata1, ydata1, zdata1)
%CREATEFIGURE1(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 22-Oct-2022 10:27:29

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create mesh
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceColor','flat');

% Create zlabel
zlabel('Accel Time (s)','FontSize',18);

% Create ylabel
ylabel('COP','FontSize',18);

% Create xlabel
xlabel('Weight Distribution','FontSize',18);

% Create title
title('Accel time sensitivty to COP and Weight Distribution',...
    'FontWeight','bold',...
    'FontSize',24);

view(axes1,[-62.0556648856501 26.2966566396487]);
grid(axes1,'on');
hold(axes1,'off');
% Create colorbar
colorbar(axes1);

