function EnduranceCOPandWD(xdata1, ydata1, zdata1)
%CREATEFIGURE1(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 22-Oct-2022 09:53:22

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create mesh
mesh1 = surf(xdata1,ydata1,zdata1,'Parent',axes1,FaceColor='flat');

% The following line demonstrates an alternative way to create a data tip.
% datatip(mesh1,0.4,0.5,98.6972333198216);
% Create datatip
datatip(mesh1,'DataIndex',6);

% Create zlabel
zlabel('Endurance Time (s)','FontSize',18);

% Create ylabel
ylabel('COP','FontSize',18);

% Create xlabel
xlabel('Weight Distribution','FontSize',18);

% Create title
title('Endurance time sensitivity to COP and Weight Distribution',...
    'FontWeight','bold',...
    'FontSize',24);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.400000005960465 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.400000005960464 0.600000023841858]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[80 100]);
view(axes1,[-4.71177492885223 8.97729713116419]);
grid(axes1,'on');
hold(axes1,'off');
% Create colorbar
colorbar(axes1);

